name: Deploy Storybook and Playwright Report to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Initialize MSW service worker
      - name: Initialize MSW service worker
        run: npx msw init public

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Build App
        run: npm run build
        env:
          GITHUB_ACTIONS: true
          VITE_ENABLE_MSW: 'true'

      # Copy MSW service worker to dist with correct base path
      - name: Copy MSW service worker
        run: cp public/mockServiceWorker.js dist/mockServiceWorker.js

      - name: Run BDD tests
        run: npm run test:bdd:ci

      - name: Copy BDD test reports to dist
        run: |
          mkdir -p dist/bdd-reports
          cp -R playwright-report/. dist/bdd-reports/
          file_count=$(find dist/bdd-reports -type f | wc -l)
          echo "Copied $file_count BDD test report files to dist/bdd-reports/"

      # Add component test coverage
      - name: Run component tests with coverage
        run: npm run test:components:coverage

      # Copy coverage reports to dist
      - name: Copy coverage reports to dist
        run: |
          mkdir -p dist/coverage
          cp -R coverage/. dist/coverage/
          file_count=$(find dist/coverage -type f | wc -l)
          echo "Copied $file_count component coverage report files to dist/coverage/"

      - name: Build Storybook
        run: npm run build-storybook

      - name: Copy Storybook to dist
        run: |
          mkdir -p dist/storybook
          cp -R storybook-static/. dist/storybook/
          echo "Copied Storybook files to dist/storybook/"

      # Add GitHub Pages deployment steps
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4